### ISSUE TITLE
Parametrization of recovery.conf

### ISSUE THREAD

**Issue by serjs** [express42/postgresql_lwrp#39]
To prevent PR's in future, like #38, we need to review current recovery.conf generation
There are several non-default params in recovery.conf which we are not define in template currently (All recovery params https://www.postgresql.org/docs/current/static/recovery-config.html)

I think, we can move default required params into attributes and extend it with hash pairs (with attribute merging request in provider) like main config is defined currently

@ikurochkin @whitew1nd any suggestions on this issue?

**Comment by whitew1nd** [comment]
🚢
